language: r
cache: 
  - packages
  - pip
r:
  - oldrel
sudo: false
warnings_are_errors: true
bioc_required: true

# Current version of xgboost fails install
# Need to force install older version using 'devtools::install_version'
#    which is done in 'before_install' (see below) 
# However 'remotes::dev_package_deps' will try to auto upgrade packages
#    Therefore, a new install command is used with 'upgrade="never"'
# These parts can be deleted once the xgboost error is fixed

before_install:
  - pyenv install 3.6.1
  - pyenv global 3.6.1
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_version("xgboost", version = "0.90.0.2", repos = "http://cran.us.r-project.org")'
  - pip install --upgrade pip
  - pip install scipy scrublet scanpy scanorama scgen bbknn

install:
- R -e 'devtools::install_deps(dep = TRUE, upgrade="never")'

addons:
  apt:
    packages:
      - libv8-dev

r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes --no-build-vignettes --as-cran"
r_github_packages:
  - jimhester/lintr
  - compbio/celda
notifications:
  slack:
    secure: sw/He3WX7Fs61DTufgG9hx7fWDhwx57zv+dYB4sr30LgKyIJNbZYSU76ZN4oPwHFGAJ0eyk/22XCuKF8/seSB2ArQuc4kFlsaeWWg1CxDqW9iR0zs91MJL3lJoUOSayy5WcWbsUxD+x8GcB37FCgoTXcveN956bfgrDb2nGrFY6QMSVsnkWi/kiMdzhR4VPzOfmAUZUcr1aDU3WN4ROwbDg89zCfu9HbVKZwyQdYZk7L2Pgg8xGIcGZkaMN1MMD/r0Wc2aVYqCOcn5qO/9CaspEBf7cd6ejVzgAl/LM4dTIPlx9E6ekQGwJXpt1Qxyc0sqVSQWFZvFkWyV3wkqX8pfSXV6ojlP2cGJt+PSQXwLHj0TKWYx7yHbw+55da/b//SVLZVHl+P6VXxQBe2hmFD6sCk3V3uq2CkxzI52bK4Wv4RRncVKIZEpFZOc9P2ik5mf6pICmLHwttlbHeDjJbQ+raYftF704xb1sOxapLwuy+c2SWKPeqOiimfZNgOK+J7JbvQvpnaiHN+3CA3wQXs1auKBwI+swvsZPAzeKssnLv/0AQmX8ckVzvXJzUvl1J73c9V2zG2F44xmIsXwzruEp6leSbeXcLifrfbfQdmaHzq4M/Z83o/fwGRzdWfG7YXDyPIabik7DOMrSUvF+wLGVTjOart8HrA4eVEkKFnRE=
r_packages:
- covr
- xgboost
after_success:
- Rscript -e 'library(covr); codecov()'
env:
  global:
  - secure: uKZUbfGfk7wBdinNFDyivyUgDt6NS0BMQhBNkBWnEWI65NH88qC6ekHmbhdtJUa7DnuOS7S97uN4fuBTNtLbOymffMIWKmA8FbmrLgt1xgGuE01EcgZscXqfkGGyeQdC3Jiz768ya7mKLM4K4Oql8ITnugWMdZYxQuA4iLEzsnVXMrNyEwZYUk5tFHKsAhL8U7TRgxcvjePP8LBRKuJT1ac6oyi7KTbz8R88LOzJX4mGra9DTXx2CUDdYEresDxF7iU/ooWMQfy6hV97PS45Kltj1Enf6XAjkd2FqbpFXLxvCO80JwhFsqID0Y5lYiITv52wCi5ehTiWh8kVGGeYbh99J9ITAO5c9yYP/2B0p9HsCdOYeek9ci4e4Si9V5wf2yDIs7UpFpwOu6gkpUwWux1tc16DS+TBKLnMNVfNQepa5OkncnONkiiXVuqN0JmvVw3ZYZZklpfdBqSG8neMTosUa8TXynHzvFgTtS8UCnVQIbH1VxjNBLJCAOnrx+HF2th6CG1A916PP3vGo+Jc0KhpE1gsKPJ/k+rrXrfsl8Tifmkm3JNWlLL2k8CO1EvkV+MmGZ0kUin1sobwmsBMG023G9BlBA+rwTZ/g4FANyzDdB9O1jMEWjUkEpgentU+C4DIA4SF+nGggVVlOz4zXKierrZnVzQi+kKDu8sCFWI=
  - secure: St4aucCBOIL5jNJQTB208i6Fu74j8f4QBYvdS1tswG+eep3wGvhbpYigk3XPR1gX8BnaIPOoVaoUuscQXb5rBPOhdU24vUl/K0tCHyDXl77wr7B0kbYPIgz7tfMEItuWjD0gXUsDBiJKznaRLj+puPJlseePld6itgrncLg/yVPrpdARqOU6SO4MY5lxBAWSKMp/ITKZmPFINiJFC/ILTAXlffBy2q8IpA51FaaMmgQ52uXeWe/7yd7LipSacywjYhz8xLmreVPaBoJ6WDYw0ymQ7Wseqf7QCGmn1XuhDu644pJVDsxF1gl7kxKGI/hpKHQoushy9VsDYM/AI0XemlIXTSxPCeNUViBvSwq5iWlHwfbaOl6eVf0ljBi8LVPRFIS91adqlLaeHg+MAWFxAlTUmABfQzUa6NZpp91/1AT4SdYlWVV1XLU31QLg1V2G9PwBHEmWVqztpZ+0rNsBxOlW0ALH9DRoYVFSRDAnGqpaSXNSV7f91XaX9TD9TjutepuCDtGJF+krwZWNKLzsAkF3MYO/BEsCdXBLJLbgDyfmOitYsQYOtoveHIeGvJaLhcuGQGzjmXgm+JwRukO8yhOUlkXa7zm7ysutLE5ytAX/1CYXGKlHzqV3h1NfUOoSH3DlJRgW/Bv+cC8iPk7KD+NmQa38ki2LzNRzOfLk37Y=
